version: '3.5'

services:
  brands-db:
    image: postgres:10.12
    environment:
      POSTGRES_USER: live-talks
      POSTGRES_PASSWORD: live-talks
      PGDATA: /data/postgres
    volumes:
      - live-talks:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - 6377:6379
    volumes:
      - redisdata:/data
    networks:
      - appnet

  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=!ChangeMe!
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - DEBUG=1
    ports:
      - "9090:80"

networks:
  appnet:
    driver: bridge

volumes:
  live-talks: ~
  redisdata: ~